//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persons.Abstractions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Persons.Abstractions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка создания команды {0}.
        /// </summary>
        internal static string CreateCommandException {
            get {
                return ResourceManager.GetString("CreateCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена сущность {0}..
        /// </summary>
        internal static string EntityNotFoundException {
            get {
                return ResourceManager.GetString("EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передан пустой объект запроса..
        /// </summary>
        internal static string NullQueryBody {
            get {
                return ResourceManager.GetString("NullQueryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передан пустой объект в репозиторий..
        /// </summary>
        internal static string PersonRepository_Insert_null_person_exception {
            get {
                return ResourceManager.GetString("PersonRepository_Insert_null_person_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfHost running on {0}.
        /// </summary>
        internal static string PersonService_Start_SelfHost {
            get {
                return ResourceManager.GetString("PersonService_Start_SelfHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfHost stopped on {0}.
        /// </summary>
        internal static string PersonService_Stop_SelfHost {
            get {
                return ResourceManager.GetString("PersonService_Stop_SelfHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonRepository connection established!.
        /// </summary>
        internal static string Repository_connection_established {
            get {
                return ResourceManager.GetString("Repository_connection_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать команду из полученных данных.
        /// </summary>
        internal static string UnableToCreateCommandFromReceivedData {
            get {
                return ResourceManager.GetString("UnableToCreateCommandFromReceivedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка валидации {0}.
        /// </summary>
        internal static string UnprocessableEntityException {
            get {
                return ResourceManager.GetString("UnprocessableEntityException", resourceCulture);
            }
        }
    }
}
