name: Main

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    
    env:
      Solution_Name: PersonAPI/PersonAPI.sln
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
              
    - name: setup-msbuild       
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: build application
      run: msbuild $env:Solution_Name -t:build -property:Configuration=$env:Configuration -m
      env:
        Configuration: ${{ matrix.configuration }}
