name: Testing - develop

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:
    env:  
      Solution_Dir: PersonAPI
      Solution_Name: PersonAPI.sln   
      Persons_Abstractions_UnitTests_Path: Persons.Abstractions.UnitTests
      Persons_IntegrationTests_Path: Persons.IntegrationTests
      Persons_Service_UnitTests_Path: Persons.Service.UnitTests
      Persons_UnitTests_Path: Persons.UnitTests

    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
              
    - name: Setup msbuild       
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup nuget
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    - name: Build application
      run: msbuild $env:Solution_Dir\$env:Solution_Name -t:build -p:Configuration=$env:Configuration -m -p:DefineConstants="LIBLOG_PUBLIC"
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Test application
      run: MsTest |
       /testcontainer:$env:Solution_Dir\$env:Persons_Abstractions_UnitTests_Path\$env:Configuration\$env:Persons_Abstractions_UnitTests_Path.dll |
       /testcontainer:$env:Solution_Dir\$env:Persons_IntegrationTests_Path\$env:Configuration\$env:Persons_IntegrationTests_Path.dll |
       /testcontainer:$env:Solution_Dir\$env:Persons_Service_UnitTests_Path\$env:Configuration\$env:Persons_Service_UnitTests_Path.dll |
       /testcontainer:$env:Solution_Dir\$env:Persons_UnitTests_Path\$env:Configuration\$env:Persons_UnitTests_Path.dll |
      env:
        Configuration: ${{ matrix.configuration }}
