name: Testing - master

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    env:  
      Solution_Dir: PersonAPI
      Solution_Name: PersonAPI.sln   
      Persons_Abstractions_UnitTests_Path: Persons.Abstractions.UnitTests
      Persons_Service_UnitTests_Path: Persons.Service.UnitTests
      Persons_UnitTests_Path: Persons.UnitTests
      Persons_IntegrationTests_Path: Persons.IntegrationTests
      Persons_Path: Persons
      Configuration: Release

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
              
    - name: Setup msbuild       
      uses: microsoft/setup-msbuild@v1
        
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1
    
    - name: Setup nuget
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Dir\$env:Solution_Name

    - name: Build application
      run: msbuild $env:Solution_Dir\$env:Solution_Name -t:build -p:Configuration=$env:Configuration -m -p:DefineConstants="LIBLOG_PUBLIC"

    - name: Create artifact   
      uses: actions/upload-artifact@v2
      with:
        name: master_build
        path: $env:Solution_Dir\$env:Persons_Path\bin\$env:Configuration\

    - name: Test Abstractions
      run: Vstest.console.exe $env:Solution_Dir\$env:Persons_Abstractions_UnitTests_Path\bin\$env:Configuration\$env:Persons_Abstractions_UnitTests_Path.dll 

    - name: Test Service
      run: Vstest.console.exe $env:Solution_Dir\$env:Persons_Service_UnitTests_Path\bin\$env:Configuration\$env:Persons_Service_UnitTests_Path.dll

    - name: Test Persons
      run: Vstest.console.exe $env:Solution_Dir\$env:Persons_UnitTests_Path\bin\$env:Configuration\$env:Persons_UnitTests_Path.dll

    - name: Test Persons.Integration
      run: Vstest.console.exe $env:Solution_Dir\$env:Persons_IntegrationTests_Path\bin\$env:Configuration\$env:Persons_IntegrationTests_Path.dll